server:
  port: 8080

spring:
  application:
    name: demo-smsmode
  datasource:
    url: jdbc:mariadb://localhost:3306/demo?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    root: debug